 
 <div>
 
 <div class="jsp2">
         <div class="jsp">
            <h1>3WA Tasks</h1>
            
            <h2>The best way to optimize your time</h2>
            
            <p>Based on the Eisenhower method, our application give you the best order to do what you have to do.</p>
            
            <div>
                <button><a class="lienButton" href="connexion.php">Se connecter</a></button>
                   <button><a class="lienButton" href="signup.php">S'inscrire</a></button>
            </div>
</div>
        
        <div>
            <img class="img" src="img/tache.jpg" alt="gestionnaire de tache photo"></img>
        </div>

</div>