
    <main>
    <div class="container">
        <form method="post">
            <label for="username">Nom :</label>
            <input type="text" id="username" name="username" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>

            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>

            <button>Se connecter</button>
        </form>
        
        <button><a href="signup.php">S'incrire</a></button>
        
        <?php if(isset($error)): ?>
        
        <p><?= $error ?></p>
        
        <?php endif; ?>
    </div>
    </main>