<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css">

    <title>Gestionnaire des tâches</title>
</head>

<body>
    
    <header>
        <nav>
            <a href="index.php">Se connecter</a>
            <a href="signup.php">S'inscrire</a>
        </nav>
    </header>
    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
</body>

</html>