
<h1>Inscrivez-vous</h1>
    <div class="container">
        <form method="post">
            
            <label for="username">Nom :</label>
            <input type="text" id="username" name="username" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>

            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>

            <button>S'inscrire</button>
        </form>
    </div>